# Generated by Django 6.1 on 2026-08-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('budget', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('production_companies', models.JSONField(blank=True, default=list)),
                ('production_countries', models.JSONField(blank=True, default=list)),
                ('spoken_languages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.JSONField(blank=True, default=list)),
                ('crew', models.JSONField(blank=True, default=list)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movies.movie')),
            ],
        ),
    ]
